services:
  frontend:
    build: .
    ports:
      - "8000:3000"
    environment:
      GRAPHITE_URL: graphite
    depends_on:
      - graphite

  graphite:
   build:
    context: docker-graphite-statsd/
    args:
      python_binary: python3
   volumes:
    - ./conf/opt/graphite/conf:/opt/graphite/conf
   ports:
    - "80:80"
    - "2003-2004:2003-2004"
    - "2023-2024:2023-2024"
    - "8125:8125/udp"
    - "8126:8126"
